### ISSUE TITLE
[Feature] Pre commit secret scanning

### ISSUE THREAD

**Issue by simonhir** [it-at-m/refarch-templates#916]
### Problem description (optional)

As i accidentally pushed some secrets to github in the past (even if only internal test credentials) and the GitHub secret detection didn't block them, it would be great to check for secrets another way.

### Desired solution

Add secret scanning as pre commit hook. E.g. https://github.com/Yelp/detect-secrets

### No duplicate

- [x] I confirm that this issue is not a duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by simonhir** [comment]
I already tried https://github.com/Yelp/detect-secrets for the exact problem with following config:

```
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: package.lock.json
```

It correctly blocked the commit with a secret in a Spring property:
```
[INFO] Stashing unstaged files to C:\Users\simon.hirtreiter\.cache\pre-commit\patch1742813417-19680.
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1
ERROR: Potential secrets about to be committed to git repo!
Secret Type: Secret Keyword
Location:    invoice-service\src\main\resources\application-local.yml:28
Possible mitigations:
  - For information about putting your secrets in a safer place, please ask in
    #security
  - Mark false positives with an inline `pragma: allowlist secret` comment
If a secret has already been committed, visit
https://help.github.com/articles/removing-sensitive-data-from-a-repository
```
